M48
; DRILL file {KiCad 7.0.2} date Sat Oct 19 10:13:17 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-19T10:13:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X108.037Y-58.781
X108.037Y-64.561
T2
X60.48Y-41.01
X68.48Y-41.01
T0
M30
